### ISSUE TITLE
Site connection exceptions

### ISSUE THREAD

**Issue by EGI-ILM** [tdviet/fedcloudclient#127]
There is a current issue in one of the sites, which is affecting the program operation:

```
$ fedcloud --version
fedcloud, version 1.2.14

$ fedcloud endpoint projects -a
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
...
File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='dashboard2.ilifu.ac.za', port=5000): Read timed out. (read timeout=10)

$
```

I cannot retrieve any information because of this single site. I would suggest to capture the exception, continue processing the rest of the sites, and at the end provide the expected output with some warning about the failing sites (in stderr or some place where it can be easily removed if the output is later processed in a script).

**Comment by tdviet** [comment]
This may be the issue of the site, not the client. An attempt to login via https://dashboard2.ilifu.ac.za/ using EGI Check-in account returned "Internal Server Error". Please verify if the site is working correctly, or contact the site admin to solve it.

So far, I am closing this ticket. Feel free to reopen it if the site is working correctly with other tools (OpenStack dashboard, OpenStack native CLI) but not with fedcloudclient.

**Comment by tdviet** [comment]
Sorry for misunderstanding your ticket. I am opening a new issue https://github.com/tdviet/fedcloudclient/issues/128 for better desciprtion

**Comment by EGI-ILM** [comment]
No problem at all. What I am trying is to be able to work with Fedcloud even if one or more sites are unavailable, like in this case. I think it will be very beneficial if a single site cannot disrupt the program operation.

If it can help, I can attempt to do a PR myself if I have time, although I am not familiar with the code.

**Comment by tdviet** [comment]
Yes, the code should be error-proofing. I tried to catch all exception, but some of them still manage to leak out :-). Thank you for reporting.

Fixing it would be simple (adding Timeout exception to this line https://github.com/tdviet/fedcloudclient/blob/master/fedcloudclient/endpoint.py#L214). And some sensible error messages should be useful instead of ignoring the errors ("pass"). I will do it when I have time.

**Comment by EGI-ILM** [comment]
Thanks. I can give it a try tomorrow if you like. I just did a "quick-and-dirty" solution at the code by adding:

```
            except (requests.exceptions.ReadTimeout) as e:
                print('site is not accessible: ', site_ep[1])
                pass
```

At https://github.com/tdviet/fedcloudclient/blob/master/fedcloudclient/endpoint.py#L190, just to have it working. Tomorrow I will check a more elegant way to fix this...

**Comment by tdviet** [comment]
OMG. I made mistake twice :) in the haste (advised you to change line 214 instead line 190). Thank you for fixing this issue. Once you finish, just make a pull request and I will merge it to the main branch.

**Comment by EGI-ILM** [comment]
I have seen that the problem with the certificates is explained [here].(https://docs.google.com/presentation/d/1aOdcceztXe8kZaIeVnioF9B0vIHLzJeklSNOdVCL3Rw/edit#slide=id.geccf457ba9_0_15):

So probably instead of my previous suggestion the code will have to be modified to actually inform the user about this situation. The problem now is that the site fails silently and there is no way for the user to know about the TLS error message. I can do a new PR if you do not have time.

**Comment by tdviet** [comment]
The "list" function in endpoint module is the "fedcloud endpoint **list**" command. By default, "click" lib uses function name as command name. If we want to change the function name, we need to configure to make "fedcloud endpoint list" to call the new function name

**Comment by EGI-ILM** [comment]
Oh I see. I knew that this could break some things.
Is it possible to use `list` externally (as a command option) but keep `endpoint_list` internally?

Perhaps something like:
```
@click.option('--format', '-f', 'format_arg_name')
def plug(format_arg_name):
    print(format_arg_name)
```

Source: https://stackoverflow.com/questions/35567753/python-click-library-rename-argument

**Comment by tdviet** [comment]
So far, I haven't found an elegant way to do it.

**Comment by tdviet** [comment]
Temporary fixed by https://github.com/tdviet/fedcloudclient/pull/129 and https://github.com/tdviet/fedcloudclient/pull/131. Further discussion in https://github.com/tdviet/fedcloudclient/issues/128 and https://github.com/tdviet/fedcloudclient/issues/130
