### ISSUE TITLE
oidc_agent_account not properly checked with the token command

### ISSUE THREAD

**Issue by sebastian-luna-valero** [tdviet/fedcloudclient#138]
Hi,

When I configure `oidc-agent` with:
```
eval $(oidc-keychain)
export OIDC_AGENT_ACCOUNT=egi
```
I get:
```
$ fedcloud token check
OIDC access token or refresh token required
```

However everything else works. I think this is due to the the code in https://github.com/tdviet/fedcloudclient/blob/master/fedcloudclient/checkin.py#L284 not checking whether `oidc_agent_account` is set.

This was also reported in https://github.com/tdviet/fedcloudclient/issues/130 but I wanted to revisit in on a separate issue for clarity.

Best regards,
Sebastian

**Comment by tdviet** [comment]
Could you clarify the use case when you need to check the tokens from `oidc-agent`? The tokens from `oidc-agent` are always valid and do not need to check again.

**Comment by sebastian-luna-valero** [comment]
No particular use case, it is more about providing a different output message for those users using `fedcloud token check` with `oidc-agent` where the connection you mention is not evident. No need to change it if you think it's not necessary.

**Comment by tdviet** [comment]
We can try to get token from `oidc-agent` in the `fedcloud token check`, and if succeeded, give a message "Access token successfully retrieved from `oidc-agent`".

**Comment by EGI-ILM** [comment]
Also related to my comments here: https://github.com/tdviet/fedcloudclient/issues/130#issuecomment-1062787103

**Comment by tdviet** [comment]
Will fix it together with https://github.com/tdviet/fedcloudclient/issues/170

**Comment by tdviet** [comment]
Fixed in https://github.com/tdviet/fedcloudclient/pull/171
