### ISSUE TITLE
"User ID" in "fedcloud openstack server list"

### ISSUE THREAD

**Issue by sebastian-luna-valero** [tdviet/fedcloudclient#145]
Hi,

I would like to understand how the following command works:
```
fedcloud openstack server list --site SITE --vo VO -c Name -c ID -c "User ID"
```

If the only `-c` values allowed by `openstack server list` are:
```
Recognized columns are ('ID', 'Name', 'Status', 'Networks', 'Image', 'Flavor').
```

Best regards,
Sebastian

**Comment by tdviet** [comment]
Try to update openstackclient to the last version

**Comment by sebastian-luna-valero** [comment]
Hi,

I am using:
```
$ openstack --version
openstack 5.8.0
```
Which seems to be the latest on available in https://pypi.org/project/python-openstackclient/

**Comment by tdviet** [comment]
So the message is outdated. Try
```
# Setting OpenStack environment
eval $(fedcloud site env --site IISAS-FedCloud --vo vo.access.egi.eu)

# Execute OpenStack CLI
openstack server list -c Name -c ID -c "User ID"
```
The second command shows all columns correctly

**Comment by sebastian-luna-valero** [comment]
Oh sorry, probably I wasn't explicit enough in my first message.

Here is how get the output above:
```
fedcloud openstack-int --site IISAS-FedCloud --vo vo.access.egi.eu

server list -c "User ID"
server list: error: unrecognized arguments: ID

server list -c User
No recognized column names in ['User']. Recognized columns are ('ID', 'Name', 'Status', 'Networks', 'Image', 'Flavor').

server list --long -c User
No recognized column names in ['User']. Recognized columns are ('ID', 'Name', 'Status', 'Task State', 'Power State', 'Networks', 'Image Name', 'Image ID', 'Flavor Name', 'Flavor ID', 'Availability Zone', 'Host', 'Properties').
```
For some reason I thought that there was a one-to-one mapping between the following to commands:
* `fedcloud openstack server list`
* `openstack server list`

That's why I don't understand how the values for `User ID` are obtained with the former and not with the latter.

Probably I am missing something obvious, sorry!

**Comment by tdviet** [comment]
The error is caused by the OpenStack internal shell that doesn't consider `"User ID"` as a single argument but as `"User"` and `"ID"`.  Try `server list -c "User\ ID" -c ID -c Name`.

fedcloud client use OpenStack command directly, so the mapping is indeed one-to-one. If you execute `openstack` without any sub-command, that will go to interactive mode and you can experience the same behavior.

**Comment by tdviet** [comment]
There are some additional columns in the codes: 

https://github.com/openstack/python-openstackclient/blob/master/openstackclient/compute/v2/server.py#L2446-L2461

I made a small test, `-c "Project ID"` is working but `-c "Security Groups"` not. Maybe the outputs depend also on the version of the OpenStack Compute server.

**Comment by sebastian-luna-valero** [comment]
Thank you!
