### ISSUE TITLE
deprecate refresh tokens

### ISSUE THREAD

**Issue by enolfc** [tdviet/fedcloudclient#161]
some time ago the use of refresh tokens + client id + client secret was seen as potentially insecure and oidc-agent was implemented instead. It's been some time since this change, should the use of refresh tokens be deprecated now?

**Comment by tdviet** [comment]
Yes, surely. We have warned about the planned deprecation more than one year, now is the time to do it: https://github.com/tdviet/fedcloudclient/blob/master/fedcloudclient/checkin.py#L109

The deprecation will require updating documentation and so on. I plan to do it after the holiday season, together with the introduction of configuration file: https://github.com/tdviet/fedcloudclient/issues/86

**Comment by tdviet** [comment]
Done in https://github.com/tdviet/fedcloudclient/pull/171
