### ISSUE TITLE
Preparation for EGI Check-in migration from MITREid to Keycloak

### ISSUE THREAD

**Issue by tdviet** [tdviet/fedcloudclient#162]
EGI Check-in is migrating from MITREid to Keycloud: 
https://docs.egi.eu/providers/check-in/sp/#client-migration-to-keycloak

FedCloud client already has parameter for providing IdP URL ` --oidc-url` also corresponding envar `OIDC_URL`, with default value to https://aai.egi.eu/oidc at the moment.

Anyways, we need to test and verify the setting with the new IdP URL and update documentations for the migration.

**Comment by sebastian-luna-valero** [comment]
Hi,

When I do:
```
export OIDC_URL=http://aai.egi.eu/auth/realms/egi
export OIDC_ACCESS_TOKEN=<mytoken>
fedcloud token list-vos
```
Or:
```
fedcloud token list-vos --oidc-access-token <mytoken> --oidc-url https://aai.egi.eu/auth/realms/egi
```
I get
```
requests.exceptions.HTTPError: 401 Client Error:  for url: https://aai.egi.eu/oidc/userinfo
```
I think this is pointing to: https://github.com/tdviet/fedcloudclient/blob/master/fedcloudclient/checkin.py#L17

Could you please have a look?

Best regards,
Sebastian

**Comment by tdviet** [comment]
I expected there will be problems. The parameter `--oidc-url` was there from beginning but was not tested thoroughly as we had only one IdP.

For your issue, the `list_vos` function uses `DEFAULT_OIDC_URL` directly that has not been updated (and should not, as the default value should be a constant, not a variable) with value from `--oidc-url`.
 https://github.com/tdviet/fedcloudclient/blob/master/fedcloudclient/checkin.py#L328

A new global variable, e.g. OIDC_URL, should be added and used everywhere. Also the `openstack` commands still do not have `OIDC_URL` as parameter, so far.

The systematic solution would be done by introducing `fedcloud.config` module that manages ALL settings and global variables, including `OIDC_URL`: https://github.com/tdviet/fedcloudclient/issues/86. Otherwise, every other solution is only a temporary hack, and will be discarded with the introduction of the new module.

I do not have capacity to do the planned changes now. If somebody can implement the `fedcloud.config` module, I will be happy to merge it, otherwise, it need to be postponed until September.

**Comment by tdviet** [comment]
Migration completed with commit https://github.com/tdviet/fedcloudclient/commit/d16820d080576bf76eedd2bf1c03444c5c626adc and released in https://github.com/tdviet/fedcloudclient/releases/tag/1.2.21
