### ISSUE TITLE
Some VOs are not found

### ISSUE THREAD

**Issue by sebastian-luna-valero** [tdviet/fedcloudclient#180]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.3.1

### Steps to reproduce

```bash
fedcloud endpoint vos -a
```

### Expected behavior

All VOs should be displayed.

### Actual behavior

Some VOs in the output below (first column) are empty.

```bash
VO                       id                                Project name             enabled    site
-----------------------  --------------------------------  -----------------------  ---------  ----------------
```

As a consequence, when I try to execute the below:

```bash
fedcloud openstack --vo <vo> --site <site> token issue -c id -f value
```

I get:

```bash
Site: <site>, VO: <vo>, command: token issue -c id -f value
Error code:  11
Error message:  VO <vo> not found on site <site>
```

Currently, as a workaround, I am currently doing:

```bash
eval $(fedcloud endpoint env --site <site> --project-id <project-id>)
openstack token issue -c id -f value
```

Am I the only one having this issue?

### Affected runtime and version

fedcloudclient@1.3.1

**Comment by tdviet** [comment]
Auto discovery of VO mapping via project properties will be used in future version for removing dependencies on site configuration files from fedcloud-catchall-operations, see https://github.com/tdviet/fedcloudclient/issues/181

**Comment by sebastian-luna-valero** [comment]
Thanks!

The VO is correctly configure in https://github.com/EGI-Federation/fedcloud-catchall-operations/

After running `fedcloud site save-config` all VOs are correctly displayed with `fedcloud endpoint vos -a`

Sorry, I don't understand. If the VO was correctly configure in https://github.com/EGI-Federation/fedcloud-catchall-operations/ in the first place, did I have to run  `fedcloud site save-config` to solve the issue?

**Comment by tdviet** [comment]
> 
> Sorry, I don't understand. If the VO was correctly configured in https://github.com/EGI-Federation/fedcloud-catchall-operations/ in the first place, why did I have to run `fedcloud site save-config` to solve the issue?

If there are no local site config files, the online site configs from github fedcloud-catchall-operations repository will be used (slow). Users can download the configs via `fedcloud site save-config`, store them locally (in `~/.config/fedcloud/site-configs`), and customize them if needed.

The local site configs on users' machine are not updated automatically, they are downloaded/updated only when the users execute `fedcloud site save-config`. Therefore, if you have outdated local config files, the VOs are not found.

Auto-updates were planned but not implemented https://github.com/tdviet/fedcloudclient/issues/15. However, a better solution via auto-discovery emerges https://github.com/tdviet/fedcloudclient/issues/181.

**Comment by sebastian-luna-valero** [comment]
I see, thanks.

I didn't have a local site config file, that's why I expected the tool to get the latest information from the GitHub repository.

Strange that I just deleted the local site config file again, but now all VOs are correctly displayed anyway.

I guess we are good to close this issue?

Many thanks for your help!
