### ISSUE TITLE
2.0-alpha1: OIDC_AGENT_ACCOUNT value not picked up from environment

### ISSUE THREAD

**Issue by sebastian-luna-valero** [tdviet/fedcloudclient#188]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0-alpha1

### Steps to reproduce

The config value shown for `oidc_agent_account`:
```bash
fedcloud config show

parameter                 value
------------------------  -----
...
oidc_agent_account        egi
...
```

is not updated with configuring the environment variable `OIDC_AGENT_ACCOUNT`:
```bash
export OIDC_AGENT_ACCOUNT=myaccount
fedcloud config show

parameter                 value
------------------------  -----
...
oidc_agent_account        egi
...
```
Subsequently I get the error:
```bash
fedcloud openstack server list
Error getting access token from oidc-agent
Error message: No account configured with that short name
Error: An access token is needed for the operation. You can specify access token directly via --oidc-access-token option or use oidc-agent via --oidc-agent-account or mytoken via --mytoken
```
which is solved when I do
```bash
fedcloud openstack --oidc-agent-account myaccount server list
```

### Expected behavior

```bash
export OIDC_AGENT_ACCOUNT=myaccount
fedcloud config show

parameter                 value
------------------------  -----
...
oidc_agent_account        myaccount
...
```

### Actual behavior

```bash
export OIDC_AGENT_ACCOUNT=myaccount
fedcloud config show
```

### Affected runtime and version

python@3.12

**Comment by sebastian-luna-valero** [comment]
Solution is to do:

```bash
export FEDCLOUD_OIDC_AGENT_ACCOUNT=myaccount
fedcloud config show
```

instead of:

```bash
export OIDC_AGENT_ACCOUNT=myaccount
fedcloud config show
```

**Comment by tdviet** [comment]
Hi Sebastian, thank you for testing. In the 2.0 version, all envvar have uniform names FEDCLOUD_<VARIABLE_NAME>. Try

`export FEDCLOUD_OIDC_AGENT_ACCOUNT=myaccount`
`export FEDCLOUD_SITE=IISAS-FedCloud`

and so on.

**Comment by sebastian-luna-valero** [comment]
Many thanks, Viet!
