### ISSUE TITLE
checkin* => oidc*

### ISSUE THREAD

**Issue by marcvs** [tdviet/fedcloudclient#3]
You are naming the OIDC stuff like the default provider you are using.

This becomes funny, if you look at the parameter `--checkin-url` in fact this is the oidc-provider-url (op-endpoint).

I think renaming this parameter would be useful

**Comment by marcvs** [comment]
Same holds for the environment variable `CHECKIN_ACCESS_TOKEN` This is actually an `OIDC_ACCESS_TOKEN` or simply `ACCESS_TOKEN`.  

Another sensible choice could be to also use `OS_ACCESS_TOKEN` which is the same token.

**Comment by tdviet** [comment]
The parameters are inherited  from egicli https://github.com/EGI-Foundation/egicli. For compatibility with egicli, the parameters will not be renamed, so far. 

The solution may be adding new parameters with the new names for the same purpose, and give warning messages if the old parameters will be deprecated and removed.

**Comment by marcvs** [comment]
Yes. I'll check the egicli for oidc-agent compatibility soon.

**Comment by tdviet** [comment]
Solved. https://github.com/tdviet/fedcloudclient/commit/9a64fb2f77d4f11a6211d277c90d4127ff052068
