### ISSUE TITLE
-f json still shows non-json output

### ISSUE THREAD

**Issue by marcvs** [tdviet/fedcloudclient#30]
Calling `fedcloud openstack quota show --site IISAS-FedCloud --vo covid19.eosc-synergy.eu -f json`

shows:
```
Site: IISAS-FedCloud, VO: covid19.eosc-synergy.eu, command: quota show -f json
{ ...}
```

**Comment by tdviet** [comment]
Please use `--json-output` or `-j` for full JSON output.  The site and VO information will be encoded inside the JSON.

```
fedcloud openstack quota show --site IISAS-FedCloud --vo covid19.eosc-synergy.eu --json-output
[
{
  "Site": "IISAS-FedCloud",
  "VO": "covid19.eosc-synergy.eu",
  "command": "quota show",
  "Exception": null,
  "Error code": 0,
  "Result": {
    "backup-gigabytes": 1000,
    "backups": 10,
...
 }
}
]
```

**Comment by tdviet** [comment]
To clarify differences between `-f json` and `--json-output` in documentation

**Comment by tdviet** [comment]
Documentation for using fedcloudclient in scripts added.
https://fedcloudclient.fedcloud.eu/scripts.html
