### ISSUE TITLE
Information on the command and site should not go to stdout

### ISSUE THREAD

**Issue by enolfc** [tdviet/fedcloudclient#33]
When trying to use the client in shell pipelines, the information about the site used should not go to stdout as this makes it hard to reuse the client in commands like this:

```shell
$ export OS_TOKEN=$(fedcloud openstack --site CESGA --vo vo.access.egi.eu token issue -c id -f value)
$ echo $OS_TOKEN
Site: CESGA, VO: vo.access.egi.eu, command: token issue -c id -f value
gAAAAABgnTf....
```

Ideally just the output of the openstack command should be dumped to stdout

**Comment by tdviet** [comment]
To add a option to suppress the printing, or check if the command is used in non-interactive mode

**Comment by enolfc** [comment]
Would it make sense to dump this in stderr?

**Comment by enolfc** [comment]
(and also check if the command is non-interactive)

**Comment by tdviet** [comment]
> Would it make sense to dump this in stderr?
Yes, also thinking about it.

The universal way for using the output of Openstack commands from the client in scripts would be to print outputs from the Openstack command in JSON format then to filter the outputs via 'jq' command, for example:

`
$ export OS_TOKEN=$(fedcloud openstack --site CESGA --vo eosc-synergy.eu token issue  --json-output | jq -r  '.[].Result.id')
`

However, for short commands like 'token issue', I agree there should be a simpler way to do it.

**Comment by tdviet** [comment]
Solved.
https://github.com/tdviet/fedcloudclient/commit/2e14363d3e9a22992e318b8654ce21524cc7dc40
