### ISSUE TITLE
-f json and all-sites

### ISSUE THREAD

**Issue by marcvs** [tdviet/fedcloudclient#5]
Maybe it's useful to provide the output of --site ALL_SITES combined with -f json (or others)  in one big json that can be parsed (as in `| jq .`)

**Comment by tdviet** [comment]
Thinking about it. We still need site info in the JSON, otherwise we don't know what output from. What about formatting the output like that:
[
    {  "Site": "IISAS-FedCloud",
       "VO": "eosc-synergy",
       "command": "image list",
       "output":[the list of images in JSON (the actual output from the command)]
    },
    {  "Site": "IFCA-LCG2",
        .... 
    },
]

**Comment by tdviet** [comment]
Solved. https://github.com/tdviet/fedcloudclient/commit/b8284c25c986911a3d6e570021a98db6d839bb2b
