### ISSUE TITLE
Most commands fail with HTTP error 401

### ISSUE THREAD

**Issue by thebe14** [tdviet/fedcloudclient#55]
I  installed the fedcloud client on Ubuntu 18.04 that had both Python 2.7 and 3.6 present as described [here](https://fedcloudclient.fedcloud.eu/install.html), followed by installation of the core trust anchor certificates. 

I obtained a refresh token for fedcloud from [here](https://aai.egi.eu/fedcloud/) and set it into env variable OIDC_ACCESS_TOKEN. I verified that I am member of _vo.access.egi.eu_.

The command `fedcloud token check` works OK.
The command `fedcloud token list-vos` fails with and exception `HTTPError: 401 Client Error:  for url: https://aai.egi.eu/oidc/userinfo`. 

Other commands also fail with HTTP errors 401 or 403. E.g. `fedcloud openstack server list -c ID -c Name --site ALL_SITES --ignore-missing-vo --vo vo.access.egi.eu` fails with many of these:

Site: IISAS-FedCloud, VO: vo.access.egi.eu, command: server list -c ID -c Name
Error code:  1
Error message:  /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
The request you have made requires authentication. (HTTP 401) (Request-ID: req-16b40c20-490d-4d93-8797-cf9605fe438c)

Help!

**Comment by thebe14** [comment]
I was using the refresh token as the access token. Can be closed.

**Comment by tdviet** [comment]
Hi @thebe14,

please make sure that you use access token for setting OIDC_ACCESS_TOKEN, not refresh token.

The access token is generated by the command in the second line at https://aai.egi.eu/fedcloud/:

```
$ curl -X POST -u ...

{
    "access_token": "ACCESS_TOKEN_HERE",
    "token_type": "Bearer",
...
}
```

The access token will expired in one hour, so consider to use oidc-agent for long-term working with fedcloudclient. Check slide 15 in the tutorial [here](https://docs.google.com/presentation/d/1aOdcceztXe8kZaIeVnioF9B0vIHLzJeklSNOdVCL3Rw/edit#slide=id.gc6a59619e8_4_3)
