### ISSUE TITLE
Add a --all-sites option instead of using ALL_SITES

### ISSUE THREAD

**Issue by enolfc** [tdviet/fedcloudclient#58]
The --site ALL_SITES is not very intuitive and not properly documented. It's easy to forget after some time without using it, so better be explicit with something like --all-sites option that avoids mispellings or confusions

**Comment by enolfc** [comment]
Option 3 does require some extra work for the parameter checking (we are doing that anyway, no?), but it would simplify checks in the long run and possible naming issues (what if a site comes named "ALL"?).

**Comment by tdviet** [comment]
We could use one of the libs based on click
- https://click-option-group.readthedocs.io/en/latest/tutorial.html#a-simple-example
- https://cloup.readthedocs.io/en/stable/pages/option-groups.html

These libs can
- nicely separate options to groups (e.g. grouping authentication options together to improve readability of the help)
- make mutual exclusion/requirement checking (e.g. one of  --site or --all-sites required)

**Comment by thebe14** [comment]
I do think EGI has a say in how sites are named and can prevent having new sites being named ALL_SITES. 
About the rhetorical question of whether we are checking that the site param does not select all sites, I added some checks to a few commands in the last PR (hopefully to all relevant commands). But we will revise that in the future, I guess.

**Comment by tdviet** [comment]
- Separated decorators for commands with and without all-sites options
- Add --all-sites option
- Add ALL-SITES keyword for tolerating misspells
