### ISSUE TITLE
Add command completion

### ISSUE THREAD

**Issue by thebe14** [tdviet/fedcloudclient#66]
This would make it so much easier to use. Depending on the command line that you already entered, pressing Tab would complete the subcommand.

**Comment by tdviet** [comment]
should be already supported, just need to be documented how to activate
```
eval "$(_FEDCLOUD_COMPLETE=bash_source fedcloud)"

```

**Comment by tdviet** [comment]
Documentation added: https://fedcloudclient.fedcloud.eu/usage.html#shell-completion
Shell completion enabled by default for Docker images
