### ISSUE TITLE
Not all command options are shown with --help

### ISSUE THREAD

**Issue by thebe14** [tdviet/fedcloudclient#69]
When you use the --help option, e.g. for `fedcloud openstack --help` the help message you get will detail all possible options (of this utility, I am not talking about OpenStack subcommands and their options). But when you try e.g. `fedcloud site --help` the site and VO options are not shown, although they apply and seem to be correctly linked in the code with decorators.

It seems that some subcommands are not shown either, e.g. `fedcloud site env`.

**Comment by tdviet** [comment]
- The command `fedcloud site --help` should not show any option but only subcommands.
```
fedcloud site --help
Usage: fedcloud site [OPTIONS] COMMAND [ARGS]...

  Site command group for manipulation with site configurations

Options:
  --help  Show this message and exit.

Commands:
  env              Generating OpenStack environment variables for site...
  list             List site IDs
  save-config      Read default site configs from GitHub and save them to...
  show             Print configuration of the specified site
  show-all         Print all site configuration
  show-project-id  Printing Keystone endpoint and project ID of the VO on...
```


- The command `fedcloud site env --help` works on my computer. Try to make fresh install or update fedcloudclient to lattest version (currently 1.2.8)
```
fedcloud site env --help
Usage: fedcloud site env [OPTIONS]

  Generating OpenStack environment variables for site and VO Does not set OS
  token, need to set separately, e.g. via oidc-token command

Options:
  --site TEXT  Name of the site or ALL_SITES  [required]
  --vo TEXT    Name of the VO  [required]
  --help       Show this message and exit.
```

**Comment by thebe14** [comment]
You are right. I was trying `fedcloud site --help` which only shows the subcommands. But if I try help on a "final" command, then it shows the options. 

This can be closed.

**Comment by thebe14** [comment]
Clarified, it work.
